### ISSUE TITLE
Segfault on archlinux

### ISSUE THREAD

**Issue by Quackdoc** [cutefishos/launcher#21]
Trying to install and run the launcher on archlinux, and I seem to have gotten a segfault in libxcb?

The total backtrace is 72 lines long but I can provide it if it would help
```hx
(gdb) bt
#0  0x00007ffff5cad27f in xcb_send_request_with_fds64 () at /usr/lib/libxcb.so.1
#1  0x00007ffff5cada6e in xcb_send_request () at /usr/lib/libxcb.so.1
#2  0x00007ffff5caf149 in xcb_intern_atom () at /usr/lib/libxcb.so.1
#3  0x00007fffe80330ab in WindowHelper::WindowHelper (this=0x5555559ff140, parent=<optimized out>, this=<optimized out>, parent=<optimized out>)
    at /usr/src/debug/fishui/fishui-0.8/src/platforms/linux/windowhelper.cpp:59
#4  0x00007fffe802e0b0 in QQmlPrivate::QQmlElement<WindowHelper>::QQmlElement (this=0x5555559ff140) at /usr/include/qt/QtQml/qqmlprivate.h:139
#5  QQmlPrivate::createInto<WindowHelper> (memory=0x5555559ff140) at /usr/include/qt/QtQml/qqmlprivate.h:166
#6  0x00007ffff77bf15b in QQmlType::create(QObject**, void**, unsigned long) const () at /usr/lib/libQt5Qml.so.5
#7  0x00007ffff78074ea in QQmlObjectCreator::createInstance(int, QObject*, bool) () at /usr/lib/libQt5Qml.so.5
#8  0x00007ffff78086a7 in QQmlObjectCreator::setPropertyBinding(QQmlPropertyData const*, QV4::CompiledData::Binding const*) ()
    at /usr/lib/libQt5Qml.so.5
#9  0x00007ffff7809f03 in QQmlObjectCreator::setupBindings(bool) () at /usr/lib/libQt5Qml.so.5
#10 0x00007ffff780e3c0 in QQmlObjectCreator::populateInstance(int, QObject*, QObject*, QQmlPropertyData const*) () at /usr/lib/libQt5Qml.so.5
#11 0x00007ffff7806e0b in QQmlObjectCreator::createInstance(int, QObject*, bool) () at /usr/lib/libQt5Qml.so.5
#12 0x00007ffff78086a7 in QQmlObjectCreator::setPropertyBinding(QQmlPropertyData const*, QV4::CompiledData::Binding const*) ()
    at /usr/lib/libQt5Qml.so.5
#13 0x00007ffff7809f03 in QQmlObjectCreator::setupBindings(bool) () at /usr/lib/libQt5Qml.so.5
#14 0x00007ffff780e3c0 in QQmlObjectCreator::populateInstance(int, QObject*, QObject*, QQmlPropertyData const*) () at /usr/lib/libQt5Qml.so.5
#15 0x00007ffff7806e0b in QQmlObjectCreator::createInstance(int, QObject*, bool) () at /usr/lib/libQt5Qml.so.5
#16 0x00007ffff7807c94 in QQmlObjectCreator::create(int, QObject*, QQmlInstantiationInterrupt*, int) () at /usr/lib/libQt5Qml.so.5
#17 0x00007ffff7807404 in QQmlObjectCreator::createInstance(int, QObject*, bool) () at /usr/lib/libQt5Qml.so.5
#18 0x00007ffff78086a7 in QQmlObjectCreator::setPropertyBinding(QQmlPropertyData const*, QV4::CompiledData::Binding const*) ()
    at /usr/lib/libQt5Qml.so.5
#19 0x00007ffff7809f03 in QQmlObjectCreator::setupBindings(bool) () at /usr/lib/libQt5Qml.so.5
#20 0x00007ffff780e3c0 in QQmlObjectCreator::populateInstance(int, QObject*, QObject*, QQmlPropertyData const*) () at /usr/lib/libQt5Qml.so.5
#21 0x00007ffff7806e0b in QQmlObjectCreator::createInstance(int, QObject*, bool) () at /usr/lib/libQt5Qml.so.5
#22 0x00007ffff7807c94 in QQmlObjectCreator::create(int, QObject*, QQmlInstantiationInterrupt*, int) () at /usr/lib/libQt5Qml.so.5
#23 0x00007ffff7807404 in QQmlObjectCreator::createInstance(int, QObject*, bool) () at /usr/lib/libQt5Qml.so.5
#24 0x00007ffff7807c94 in QQmlObjectCreator::create(int, QObject*, QQmlInstantiationInterrupt*, int) () at /usr/lib/libQt5Qml.so.5
#25 0x00007ffff77ac2e7 in QQmlIncubatorPrivate::incubate(QQmlInstantiationInterrupt&) () at /usr/lib/libQt5Qml.so.5
#26 0x00007ffff77a3684 in QQmlEnginePrivate::incubate(QQmlIncubator&, QQmlContextData*) () at /usr/lib/libQt5Qml.so.5
```

**Comment by Quackdoc** [comment]
Seems like this is a wayland specific issue
